### ISSUE TITLE
_.push() doesn't support array of tasks

### ISSUE THREAD

**Issue by dev101** [astur/icrawler#1]
Как сказано в документации, _.pushшить можно не только скаляры, но и массивы urlей.
Но в этом случае `tasks` из [newTasksResolve](https://github.com/astur/icrawler/blob/master/index.js#L71) будет не массивом урлов, а **массивом массивов** урлов, и `newTasksResolve` будет кидать исключение, потом что [`tasks[i]`](https://github.com/astur/icrawler/blob/master/index.js#L74) будет не строкой, как ожидается, а массивом.
Чтобы вопроизвести, достаточно сделать `_.push([url1, url2])`, получится

```
TypeError: Parameter "url" must be a string, not undefined
    at Url.parse (url.js:87:11)
    at urlParse (url.js:81:5)
    at Url.resolve (url.js:641:29)
    at urlResolve (url.js:637:40)
    at newTasksResolve (\node_modules\icrawler\index.js:80:32)
    at onParse (\node_modules\icrawler\index.js:101:23)
    at Object.module.exports._.cb (\node_modules\icrawler\index.js:127:17)

```

Нужно переписать `newTasksResolve` с учётом того, что в tasks могут быть как скаляры, так и массивы, причём вперемешку.

**Comment by astur** [comment]
Точно, есть такое. На днях поправлю.
Спасибо за багрепорт.

**Comment by astur** [comment]
Fixed in v2.6.5

**Comment by dev101** [comment]
я бы предложил сделать менее изящно, но более надежно ... [часто пишут](https://stackoverflow.com/a/22747272/1047880), что ты не сможешь вставить через `.apply()` массив размером более 65536 (или какой-то другой фикс. величины) элементов.

**Comment by astur** [comment]
ну, это примерно то же самое, что передать функции более 65536 параметров. Есть две причины, по которым меня не беспокоит это ограничение:
1. вряд ли в интернете есть хоть одна страница, с которой имеет смысл пушить более 65536 новых ссылок.
2. модуль icrawler, к настоящему моменту, состоит, по большей части, из технического долга, и внедрять в него неизящные но надёжные решения стоит только после основательного рефакторинга и покрытия тестами.

**Comment by dev101** [comment]
Согласен.
